### ISSUE TITLE
852a334 and on gives same cards every time

### ISSUE THREAD

**Issue by ajmac** [girst/solvitaire#4]
As per the title, from commit 852a334 onwards the cards dealt are the same for me every time (in sol, haven't tried spider.)

**Comment by ansem-of-nexus** [comment]
spider is free of this problem, just sol.
sol.c line 119:seed = 1550150477
it's hard coding the seed of the game so it can't change, delete it from your file and remake sol, then it works fine

**Comment by girst** [comment]
yeah, i'm an idiot. i tried to debug something in the upcoming freecell mode and accidentally committed that. i noticed today, and removed that, so it should be fixed :s
