### ISSUE TITLE
I think the game is broken 

### ISSUE THREAD

**Issue by HugoDs21** [girst/solvitaire#5]
Im stuck. The game has no more options to play or im just bad

**Comment by girst** [comment]
I honestly don't know if you're trolling.

**Comment by HugoDs21** [comment]
I was being serious. Is there any "error message" if the game become unwinnable?
I can be just bad but for two times my game was impossible to do any play.

**Comment by girst** [comment]
there's no error message when there aren't any more moves to play or 
when the game becomes impossible to win (i haven't implemented a solver, 
after all). a quick internet search suggests that players win on average 
1 out of 11.5 games, so you're well within the margin of error ;-)
